name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: |
          curl -X POST -d '{}' https://api.netlify.com/build_hooks/6a1d219a980d5aed541cdb1b
